name: Sync Main to Claude-Code Branch

on:
  workflow_dispatch:
  schedule:
    # Run daily at 2 AM UTC (optional - remove if you don't want automatic runs)
    - cron: '0 2 * * *'

jobs:
  sync-to-claude-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: |
          git fetch origin

      - name: Check if claude-code branch exists
        run: |
          if ! git ls-remote --heads origin claude-code | grep claude-code; then
            echo "❌ Error: claude-code branch does not exist!"
            echo "Please create the claude-code branch first before running this workflow."
            exit 1
          else
            echo "✅ claude-code branch exists, proceeding with sync."
          fi

      - name: Create sync branch
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="sync-main-to-claude-code-$TIMESTAMP"
          git checkout -b "$BRANCH_NAME" origin/main
          echo "SYNC_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Push sync branch
        run: |
          git push origin "$SYNC_BRANCH"

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Sync main to claude-code branch - ${new Date().toISOString().split('T')[0]}`,
                head: process.env.SYNC_BRANCH,
                base: 'claude-code',
                body: `
                This PR syncs the latest changes from main branch to claude-code branch.
                
                ## Changes
                - Latest commits from main branch
                - Generated automatically by sync workflow
                
                ## Review Notes
                - **Merge conflicts are expected and should be resolved manually**
                - This workflow creates the PR but doesn't attempt to resolve conflicts
                - Review and merge when ready, resolving any conflicts as needed
                
                **Auto-generated by main-to-claude-code sync workflow**
                `
              });
              
              console.log(`Created PR #${pr.number}: ${pr.html_url}`);
            } catch (error) {
              if (error.message.includes('No commits between')) {
                console.log('No new commits to sync - branches are already up to date');
              } else {
                throw error;
              }
            } 