name: Sync with Upstream LiteLLM Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to sync from upstream (e.g., v3.4.3)'
        required: true
        type: string

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/BerriAI/litellm.git || true
          git fetch upstream

      - name: Create sync branch
        run: |
          BRANCH_NAME="sync-upstream-${{ github.event.inputs.release_tag }}"
          git checkout -b "$BRANCH_NAME"
          echo "SYNC_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Merge upstream release
        run: |
          git merge upstream/${{ github.event.inputs.release_tag }} --no-edit || {
            echo "Merge conflicts detected. Creating PR with conflicts for manual resolution."
            git add .
            git commit -m "Merge upstream ${{ github.event.inputs.release_tag }} with conflicts" || true
          }

      - name: Push sync branch
        run: |
          git push origin "$SYNC_BRANCH"

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Sync with upstream LiteLLM ${{ github.event.inputs.release_tag }}`,
              head: process.env.SYNC_BRANCH,
              base: 'main',
              body: `
              This PR syncs the repository with upstream LiteLLM release ${{ github.event.inputs.release_tag }}.
              
              ## Changes
              - Merged changes from upstream tag: ${{ github.event.inputs.release_tag }}
              
              ## Review Notes
              - Please review all changes carefully before merging
              - Check for any breaking changes in the upstream release
              - Resolve any merge conflicts if they exist
              
              **Auto-generated by sync workflow**
              `
            });
            
            console.log(`Created PR #${pr.number}: ${pr.html_url}`); 