name: Sync with Upstream LiteLLM Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to sync from upstream (e.g., v3.4.3)'
        required: true
        type: string

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/BerriAI/litellm.git || true
          git fetch upstream --tags
          echo "Available upstream tags:"
          git tag -l | grep -E "^v[0-9]" | tail -10

      - name: Verify upstream tag exists
        run: |
          if ! git rev-parse --verify "${{ github.event.inputs.release_tag }}" >/dev/null 2>&1; then
            echo "❌ Error: Tag ${{ github.event.inputs.release_tag }} not found in repository!"
            echo "Available recent tags:"
            git tag -l | grep -E "^v[0-9]" | tail -5
            exit 1
          else
            echo "✅ Tag ${{ github.event.inputs.release_tag }} found"
          fi

      - name: Create sync branch from upstream release
        run: |
          BRANCH_NAME="sync-upstream-${{ github.event.inputs.release_tag }}"
          git checkout -b "$BRANCH_NAME" "${{ github.event.inputs.release_tag }}"
          echo "SYNC_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Branch created from tag: ${{ github.event.inputs.release_tag }}"
          echo "Latest commit in sync branch:"
          git log --oneline -1

      - name: Push sync branch
        run: |
          git push origin "$SYNC_BRANCH"
        continue-on-error: false

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Sync with upstream LiteLLM ${{ github.event.inputs.release_tag }}`,
                head: process.env.SYNC_BRANCH,
                base: 'main',
                body: `
                This PR syncs the repository with upstream LiteLLM release ${{ github.event.inputs.release_tag }}.
                
                ## Changes
                - Updated to upstream tag: ${{ github.event.inputs.release_tag }}
                - Contains pure upstream release content
                
                ## Review Notes
                - Please review all changes carefully before merging
                - Check for any breaking changes in the upstream release
                - This brings your main branch up to date with upstream
                
                **Auto-generated by sync workflow**
                `
              });
              
              console.log(`✅ Created PR #${pr.number}: ${pr.html_url}`);
            } catch (error) {
              if (error.message.includes('No commits between')) {
                console.log('⚠️ No differences found between branches - already up to date');
              } else {
                console.error('❌ Error creating PR:', error.message);
                throw error;
              }
            } 